name: actions-slack
description: Notify via slack in GitHub Actions workflow
author: innocarpe
inputs:
  success_text:
    description: Slack message when succeeded.
    default: "Succeeded 🚀"
  failure_text:
    description: Slack message when failed.
    default: "Failed 😱"
  cancelled_text:
    description: Slack message when cancelled.
    default: "Cancelled ⚠️"
runs:
  using: 'node12'
  main: lib/main.js
branding:
  icon: bell
  color: black