name: Slack Mainline
on:
  push:
    branches:
      - master
      - releases/*

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Normal Case Check
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }} # Required
          success_text: 'Step Succeeded 🚀' # Optional
          failure_text: 'Step Failed 😱' # Optional
          cancelled_text: 'Step Cancelled ⚠️' # Optional
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Required

      # Message with group mention, github actor, github ref
      - name: Advanced Case Check 
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }} # Required
          success_text: '<!subteam^S1ABC2DEF> @${{ github.actor }} just started the workflow for `${{ github.ref }}` 🚀'
          failure_text: 'Step Failed 😱' # Optional
          cancelled_text: 'Step Cancelled ⚠️' # Optional
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Required

      - name: Succeeded Check
        uses: innocarpe/actions-slack@v1
        with:
          status: success
          success_text: 'Step Succeeded 🚀'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Failed Check
        uses: innocarpe/actions-slack@v1
        with:
          status: failure
          failure_text: 'Step Failed 😱'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Cancelled Check
        uses: innocarpe/actions-slack@v1
        with:
          status: cancelled
          cancelled_text: 'Step Cancelled ⚠️'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Default Check
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
